// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvgtaaatglghlftrsbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Z3RhYWF0Z2xnaGxmdHJzYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTYzMDUsImV4cCI6MjA2NjYzMjMwNX0.5WoocvzfB51ApXKI8cFxtaNYZQVFjlDXrtYm0McXUbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);